#!/usr/bin/env python3
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path


def load_jsonl(path: Path):
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def excerpt(path: Path, limit=12):
    if not path.exists():
        return "[missing raw artifact]"
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    return "\n".join(lines[:limit]).strip() or "[empty]"


def main():
    run_dir = Path(sys.argv[1])
    run = json.loads((run_dir / "run.json").read_text(encoding="utf-8"))
    evidence = load_jsonl(run_dir / "evidence" / "index.jsonl")
    observations = load_jsonl(run_dir / "normalized" / "observations.jsonl")
    findings = load_jsonl(run_dir / "findings" / "findings.jsonl")
    confidence = json.loads((run_dir / "findings" / "confidence.json").read_text(encoding="utf-8"))

    obs_by_type = defaultdict(list)
    for obs in observations:
        obs_by_type[obs["type"]].append(obs)

    sev_counts = Counter(f["severity"] for f in findings)
    package_name = run["target"]["value"]
    package_meta = obs_by_type["android.manifest.package_meta"][0]["attributes"] if obs_by_type["android.manifest.package_meta"] else {}

    out = []
    out.append(f"# APDIF Analyst Report: {package_name}")
    out.append("")
    out.append(f"Generated: {run.get('finished_at') or run.get('started_at')}")
    out.append(f"Run ID: {run['run_id']}")
    out.append(f"Case: {run['case_id']}")
    out.append("")
    out.append("## Executive Summary")
    out.append(f"- Confidence score: {confidence['score']}/100")
    out.append(f"- Findings: {len(findings)} total")
    out.append(f"- Severity counts: critical={sev_counts.get('critical',0)} high={sev_counts.get('high',0)} medium={sev_counts.get('medium',0)} low={sev_counts.get('low',0)} info={sev_counts.get('info',0)}")
    out.append("")
    out.append("## Scope and Collection Integrity")
    out.append(f"- Target kind: {run['target']['kind']}")
    out.append(f"- Required collectors: {', '.join(confidence['required_collectors']) or 'none'}")
    out.append(f"- Completed collectors: {', '.join(confidence['completed_collectors']) or 'none'}")
    out.append(f"- Unmet controls: {', '.join(confidence['unmet_controls']) or 'none'}")
    out.append("")
    out.append("## Target Identity")
    out.append(f"- Package or artifact: `{package_name}`")
    out.append(f"- Profile: `{run.get('profile', 'baseline')}`")
    if package_meta.get("target_sdk"):
        out.append(f"- Target SDK: `{package_meta.get('target_sdk')}`")
    if package_meta.get("min_sdk"):
        out.append(f"- Min SDK: `{package_meta.get('min_sdk')}`")
    if package_meta.get("uses_cleartext_traffic") not in (None, ""):
        out.append(f"- usesCleartextTraffic: `{package_meta.get('uses_cleartext_traffic')}`")
    if package_meta.get("allow_backup") not in (None, ""):
        out.append(f"- allowBackup: `{package_meta.get('allow_backup')}`")
    out.append("")
    out.append("## Severity Overview")
    for severity in ("critical", "high", "medium", "low", "info"):
        out.append(f"- {severity}: {sev_counts.get(severity, 0)}")
    out.append("")
    out.append("## Key Findings")
    if findings:
        for finding in findings:
            out.append(f"### {finding['severity'].upper()} {finding['finding_id']} {finding['title']}")
            out.append(f"- What was observed: {finding['summary']}")
            out.append(f"- Why it matters: {finding['why_it_matters']}")
            out.append(f"- Recommended next step: {finding['remediation']}")
            out.append(f"- Evidence IDs: {', '.join(finding['evidence_ids']) or 'none'}")
            out.append("")
    else:
        out.append("No findings were generated by the current rule set.")
        out.append("")
    out.append("## Attack Surface Map")
    components = obs_by_type["android.manifest.component"]
    if components:
        for obs in components:
            attrs = obs["attributes"]
            out.append(
                f"- {attrs.get('component_type','component')}: `{attrs.get('name','unknown')}` "
                f"owner=`{attrs.get('owner','unknown')}` "
                f"exported=`{attrs.get('effective_exported','unknown')}` "
                f"reason=`{attrs.get('export_reason','unknown')}` "
                f"permission=`{attrs.get('permission','')}`"
            )
    else:
        out.append("- No structured component inventory was normalized.")
    out.append("")
    out.append("## Permissions and AppOps")
    perms = obs_by_type["android.permission.requested"]
    appops = obs_by_type["android.appops.entry"]
    if perms:
        seen_permissions = []
        seen_names = set()
        for obs in perms:
            name = obs["attributes"]["name"]
            if name in seen_names:
                continue
            seen_names.add(name)
            seen_permissions.append(name)
        out.append("- Requested permissions:")
        for name in seen_permissions[:20]:
            out.append(f"  - `{name}`")
    else:
        out.append("- Requested permissions: none normalized")
    if appops:
        out.append("- AppOps excerpts:")
        for obs in appops[:10]:
            out.append(f"  - `{obs['attributes']['line']}`")
    else:
        out.append("- AppOps excerpts: none normalized")
    out.append("")
    out.append("## Exported Components")
    exported = [obs for obs in components if str(obs["attributes"].get("effective_exported", "")).lower() == "true"]
    if exported:
        for obs in exported:
            attrs = obs["attributes"]
            out.append(
                f"- `{attrs.get('name','unknown')}` "
                f"type=`{attrs.get('component_type','')}` "
                f"owner=`{attrs.get('owner','unknown')}` "
                f"reason=`{attrs.get('export_reason','unknown')}`"
            )
    else:
        out.append("- No explicitly exported components were normalized.")
    out.append("")
    out.append("## Deep Links and Intent Handlers")
    deep_links = obs_by_type["android.manifest.intent_filter"] + obs_by_type["android.package.intent_hint"]
    if deep_links:
        for obs in deep_links[:20]:
            out.append(f"- `{json.dumps(obs['attributes'], sort_keys=True)}`")
    else:
        out.append("- No deep link observations were normalized.")
    out.append("")
    out.append("## Local Storage")
    storage = obs_by_type["android.storage.entry"]
    if storage:
        for obs in storage[:20]:
            out.append(f"- {obs['attributes'].get('section','unknown')}: `{obs['attributes'].get('line','')}`")
    else:
        out.append("- No storage observations were normalized.")
    out.append("")
    out.append("## WebView and Embedded Browser Risk")
    webview = obs_by_type["android.strings.webview_indicator"]
    if webview:
        for obs in webview[:20]:
            out.append(f"- `{obs['attributes']['value']}`")
    else:
        out.append("- No WebView indicators were normalized.")
    out.append("")
    out.append("## Runtime Observations")
    runtime = obs_by_type["android.runtime.snapshot_entry"]
    if runtime:
        for obs in runtime[:20]:
            out.append(f"- {obs['attributes'].get('section','unknown')}: `{obs['attributes'].get('line','')}`")
    else:
        out.append("- No runtime observations were normalized.")
    out.append("")
    out.append("## Control Coverage Matrix")
    for collector in confidence["required_collectors"]:
        state = "complete" if collector in confidence["completed_collectors"] else "missing"
        out.append(f"- {collector}: {state}")
    out.append("")
    out.append("## Evidence Index")
    for item in evidence:
        out.append(f"- {item['evidence_id']} `{item['collector_id']}` status=`{item['collector_status']}` path=`{item['raw_path']}`")
    out.append("")
    out.append("## Raw Evidence Appendix")
    for item in evidence:
        raw_path = Path(item["raw_path"])
        out.append(f"<details><summary>{item['evidence_id']} {item['collector_id']}</summary>")
        out.append("")
        out.append(f"Path: `{raw_path}`")
        out.append(f"SHA256: `{item.get('sha256','')}`")
        out.append("")
        out.append("```text")
        if item.get("content_type", "").startswith("text/") and raw_path.exists():
            out.append(raw_path.read_text(encoding="utf-8", errors="replace"))
        elif raw_path.exists():
            out.append("[non-text artifact preserved on disk]")
        else:
            out.append("[missing raw artifact]")
        out.append("```")
        out.append("</details>")
        out.append("")
    out.append("## Android Glossary for Analysts")
    out.append("- Exported component: an Android app component reachable from outside the package boundary.")
    out.append("- BROWSABLE intent filter: an activity entry point invokable by browsers and other apps.")
    out.append("- AppOps: runtime operation policy state maintained by Android in addition to manifest permissions.")
    out.append("- run-as: a shell mechanism that can inspect app-private storage for debuggable or otherwise permitted packages.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
